/* eslint-disable */
// @ts-nocheck

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Monitor(props) {
  const { nodes, materials } = useGLTF('/r3f/models/monitor.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.024}>
        <group position={[10.399, 0.945, 4.663]} rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_1.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_1.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_2.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_3.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_2.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_4.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_3.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_5.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_4.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_6.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_5.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_7.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_6.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_8.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_7.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_9.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_8.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_10.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_9.geometry}
            material={materials.Color_M09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_11.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_12.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_10.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_13.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_11.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_14.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_15.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_12.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_16.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_13.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_17.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_14.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_18.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_15.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_19.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_16.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_20.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_17.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_21.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_18.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_22.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_19.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_23.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_20.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_24.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_21.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_25.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_22.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_26.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_27.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_28.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_23.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_29.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_24.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_30.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_25.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_31.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_26.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_27.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_32.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_28.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_33.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_29.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_34.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_30.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_35.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_31.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_36.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_32.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_37.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_33.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_38.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_34.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_39.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_35.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_40.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_36.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_41.geometry}
            material={materials.Color_H05}
          />
        </group>
        <group position={[1.378, -0.709, 3.228]} rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_42.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_43.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_44.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_45.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_46.geometry}
            material={materials.Color_M08}
          />
        </group>
        <group position={[5.838, 3.15, 0]} rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_47.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_48.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_37.geometry}
            material={materials.Color_H05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_49.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_50.geometry}
            material={materials.Color_M08}
          />
          <lineSegments
            geometry={nodes.Material2_51.geometry}
            material={materials.edge_color303030255}
          />
        </group>
        <group
          position={[9.843, 4.796, 0.32]}
          rotation={[-Math.PI / 4, 0, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_52.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_53.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_54.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_38.geometry}
            material={materials.Color_M07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_55.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_56.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_39.geometry}
            material={materials.Color_M06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_57.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_40.geometry}
            material={materials.Color_M06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_58.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_41.geometry}
            material={materials.Color_M06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_59.geometry}
            material={materials.Color_M08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material3_42.geometry}
            material={materials.Color_M06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Material2_60.geometry}
            material={materials.Color_M08}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/r3f/models/monitor.glb')
